/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c9adbed8-b50e-4eb3-a45b-c3629f59bfc4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Z7aQcSHf6",
    "aws_user_pools_web_client_id": "okre6v2phqgl2c326mdk8m46j",
    "oauth": {}
};


export default awsmobile;
